const products = [
    // Electronics
    {
      id: 1,
      name: "Smartphone", slug:"smartphone",
      price: 699.99,
      description: "Latest model with high-resolution camera.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 2,
      name: "Laptop", slug: "laptop",
      price: 1299.99,
      description: "Powerful laptop for gaming and productivity.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/459653/pexels-photo-459653.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 3,
      name: "Wireless Earbuds", slug: "wireless earbuds",
      price: 149.99,
      description: "High-quality sound with noise cancellation.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/28843742/pexels-photo-28843742/free-photo-of-stylish-floral-earphone-case-and-airpods.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 4,
      name: "Smartwatch", slug: "smartwatch",
      price: 249.99,
      description: "Fitness tracker with heart rate monitor.",
      category: "Electronics",
      inStock: false,
      imageUrl: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 5,
      name: "4K TV", slug: "4K TV",
      price: 899.99,
      description: "Ultra HD smart TV with streaming capabilities.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/5490302/pexels-photo-5490302.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 6,
      name: "Bluetooth Speaker", slug: "bluetooth speaker",
      price: 99.99,
      description: "Portable speaker with rich sound quality.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/9767549/pexels-photo-9767549.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 7,
      name: "Digital Camera", slug: "digital camera",
      price: 499.99,
      description: "High-resolution camera for photography enthusiasts.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1528851/pexels-photo-1528851.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 8,
      name: "Gaming Console", slug: "gaming console",
      price: 499.99,
      description: "Next-gen gaming console with immersive experience.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/4522992/pexels-photo-4522992.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 9,
      name: "Laptop Stand", slug: "laptop stand",
      price: 39.99,
      description: "Ergonomic stand for comfortable laptop use.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/6045235/pexels-photo-6045235.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 10,
      name: "HDMI Cable", slug: "hdmi cable",
      price: 14.99,
      description: "High-speed HDMI cable for connecting devices.",
      category: "Electronics",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/4779730/pexels-photo-4779730.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  
    // Clothing
    {
      id: 11,
      name: "T-Shirt", slug: "t-shirt",
      price: 19.99,
      description: "100% cotton, available in multiple colors.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/2112651/pexels-photo-2112651.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 12,
      name: "Jeans", slug: "jeans",
      price: 49.99,
      description: "Stylish denim jeans with a relaxed fit.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1082528/pexels-photo-1082528.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 13,
      name: "Jacket", slug: "jacket",
      price: 89.99,
      description: "Warm and stylish jacket for winter.",
      category: "Clothing",
      inStock: false,
      imageUrl: "https://images.pexels.com/photos/28919276/pexels-photo-28919276/free-photo-of-elegant-blue-suit-on-artistic-canvas.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 14,
      name: "Dress", slug: "dress",
      price: 59.99,
      description: "Elegant dress perfect for any occasion.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/2065195/pexels-photo-2065195.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 15,
      name: "Sweater", slug: "sweater",
      price: 39.99,
      description: "Cozy sweater for chilly days.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/5603009/pexels-photo-5603009.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 16,
      name: "Shorts", slug: "shorts",
      price: 29.99,
      description: "Comfortable shorts for summer wear.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1963233/pexels-photo-1963233.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 17,
      name: "Coat",slug: "coat",
      price: 99.99,
      description: "Stylish coat to keep you warm in winter.",
      category: "Clothing",
      inStock: false,
      imageUrl: "https://images.pexels.com/photos/158648/girl-coat-old-coat-brown-coat-158648.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 18,
      name: "Activewear Leggings", slug: "activewear leggings",
      price: 39.99,
      description: "Comfortable leggings for workouts.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/5310782/pexels-photo-5310782.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 19,
      name: "Skirt", slug: "skirt",
      price: 34.99,
      description: "Fashionable skirt suitable for any occasion.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/28709229/pexels-photo-28709229/free-photo-of-bohemian-woman-posing-outdoors-in-vibrant-outfit.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 20,
      name: "Pajamas", slug: "pajamas",
      price: 29.99,
      description: "Soft pajamas for a good night's sleep.",
      category: "Clothing",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/4056466/pexels-photo-4056466.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  
    // Accessories
    {
      id: 21,
      name: "Backpack",slug: "backpack",
      price: 39.99,
      description: "Durable backpack for school or travel.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/732632/pexels-photo-732632.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 22,
      name: "Sunglasses", slug: "sunglasses",
      price: 29.99,
      description: "Stylish sunglasses with UV protection.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/2703963/pexels-photo-2703963.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 23,
      name: "Watch",slug: "watch",
      price: 149.99,
      description: "Elegant watch suitable for any outfit.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 24,
      name: "Hat", slug: "hat",
      price: 24.99,
      description: "Fashionable hat for sun protection.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/984619/pexels-photo-984619.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 25,
      name: "Scarf", slug: "scarf",
      price: 19.99,
      description: "Warm scarf for cold weather.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/2120584/pexels-photo-2120584.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 26,
      name: "Belt", slug: "belt",
      price: 34.99,
      description: "Classic leather belt for everyday use.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1023937/pexels-photo-1023937.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 27,
      name: "Wallet", slug: "wallet",
      price: 49.99,
      description: "Sleek wallet with multiple card slots.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/4452518/pexels-photo-4452518.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 28,
      name: "Jewelry Set",slug: "jewelry set",
      price: 89.99,
      description: "Elegant jewelry set for special occasions.",
      category: "Accessories",
      inStock: false,
      imageUrl: "https://images.pexels.com/photos/4295004/pexels-photo-4295004.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 29,
      name: "Phone Case", slug: "phone case",
      price: 14.99,
      description: "Durable phone case to protect your device.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1670768/pexels-photo-1670768.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 30,
      name: "Umbrella",slug: "umbrella",
      price: 19.99,
      description: "Compact umbrella for unexpected rain.",
      category: "Accessories",
      inStock: true,
      imageUrl: "https://images.pexels.com/photos/1715161/pexels-photo-1715161.jpeg?auto=compress&cs=tinysrgb&w=600s",
    },
  ];

  export default products